Models/ContasModel.cs
namespace ByteBankMvc.Models {
    public class ContasModel {
        public int Id { get; set; }
        public string Cpf { get; set; }
        public string Titular { get; set; }
        public string Senha { get; set; }
        public double Saldo { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace ByteBankMvc.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HomeModel.cs
namespace ByteBankMvc.Models {
    public class HomeModel {
        
    }
}

Controllers/HomeController.cs
using ByteBankMvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ByteBankMvc.Controllers {
    public class HomeController : Controller {
        public IActionResult Index () {
           return View();
        }

        public IActionResult Privacy () {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error () {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ListarContasController.cs
using ByteBankMvc.Models;
using ByteBankMvc.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ByteBankMvc.Controllers {
    public class ListarContasController : Controller {

        private readonly IContasRepositorio _contasRepositorio;
        public ListarContasController (IContasRepositorio contasRepositorio) {
            _contasRepositorio = contasRepositorio;
        }

        public IActionResult Index () {
           List<ContasModel> contas = _contasRepositorio.BuscarTodos();
            return View(contas);
        }

        public IActionResult Criar () {
            return View();
        }

        public IActionResult Editar (int id) {
            ContasModel conta =  _contasRepositorio.ListPorId(id);
            return View(conta);
        }

        public IActionResult ApagarConfirmacao (int id) {
            ContasModel conta = _contasRepositorio.ListPorId(id);
            return View(conta);
        }




        public IActionResult Apagar(int id) {
            _contasRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Criar (ContasModel conta) {
            _contasRepositorio.Adicionar(conta);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar (ContasModel conta) {
            _contasRepositorio.Atualizar(conta);
            return RedirectToAction("Index");
        }

    }
}

Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;

namespace ByteBankMvc.Controllers {
    public class TransacaoController : Controller {
        public IActionResult Index () {
            return View();
        }

        public IActionResult Deposito () {
            return View();
        }

        public IActionResult Transferir () {
            return View();
        }

        public IActionResult Saque () {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo ao Byte Bank!</h1>
    <p>Sistema Bancário Sharp Coders</p>
</div>

Views/ListarContas/ApagarConfirmacao.cshtml
@model ContasModel
@{
    ViewData["Title"] = "Confirmação apagar usuário";
}

<div class="text-center">
    <h3>Realmente deseja remover o usuário (@Model.Titular)?</h3>
</div>
<br />
<div class="text-center">
    <a class="btn btn-primary" role="button" asp-controller="ListarContas" asp-action="Index">Cancelar</a>
    <a class="btn btn-danger" role="button" asp-controller="ListarContas" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar</a>
</div>

Views/ListarContas/Criar.cshtml
@model ContasModel

@{
    ViewData["Title"] = "Criar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Cadastro de Usuário</h1>

</div>

<form asp-controller="ListarContas" asp-action="Criar" method="post">
  <div class="form-group">
    <label for="cpf">CPF</label>
    <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF">
  </div>

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Titular" class="form-control" placeholder="Digite o seu nome">
    </div>

    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Coloque uma senha">
    </div>

    <div class="form-group">
        <label for="saldo">Saldo $</label>
        <input type="number" asp-for="Saldo" class="form-control" placeholder="Coloque o Saldo">
    </div>
    <br />
  <button type="submit" class="btn btn-primary">Adicionar</button>
  <a class="btn btn-secondary" asp-controller = "ListarContas" asp-action="Index" role="button">Voltar</a>
</form>

Views/ListarContas/Editar.cshtml
@model ContasModel
@{
    ViewData["Title"] = "Editar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Editar Usuário</h1>

</div>

<form asp-controller="ListarContas" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF">
    </div>

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Titular"  class="form-control" placeholder="Digite o seu nome">
    </div>

    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Coloque uma senha">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="ListarContas" asp-action="Index" role="button">Voltar</a>
</form>

Views/ListarContas/Index.cshtml
@model List<ContasModel>

@{
    ViewData["Title"] = "Listar Contas";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="ListarContas" asp-action="Criar"> <!--Esse asp-controller é para criar o link para minha página de criar novo usuário-->
            Inserir novo usuário
        </a>
    </div>

    <h1 class="display-4">Listagem de Usuários</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">CPF</th>
                <th scope="col">Titular</th>
                <th scope="col">Saldo</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any()) {

                foreach (ContasModel contas in Model) {
                    <tr>
                        <th scope="row">@contas.Id</th>
                        <td>@contas.Cpf</td>
                        <td>@contas.Titular</td>
                        <td>R$ @contas.Saldo.ToString("F2")</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-outline-primary" asp-route-id="@contas.Id" asp-controller="ListarContas" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-outline-primary" asp-route-id="@contas.Id" asp-controller="ListarContas" asp-action="ApagarConfirmacao">Exluir</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>


</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ByteBankMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ByteBankMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Byte Bank</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListarContas" asp-action="Index">Listar Contas Registradas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ByteBankMvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Transacao/Deposito.cshtml
@{
    ViewData["Title"] = "Editar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Depositar Dinheiro</h1>

</div>

<form>
    <div class="form-group">
        <label for="deposito"> <h5>Quantidade a Ser Depositado R$</h5> </label>
        <input type="number" class="form-control" placeholder="R$">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Confirmar</button>
    <a class="btn btn-secondary" asp-controller="Transacao" asp-action="Index" role="button">Voltar</a>
</form>

Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transações Bancárias";
}

<div class="text-center">
    <h3>Trasações Bancárias</h3>
</div>
<br />
<div class="text-center">
    <a class="btn btn-primary" role="button" asp-controller="Transacao" asp-action="Deposito">Depositar</a>
    <a class="btn btn-primary" role="button" asp-controller="Transacao" asp-action="Transferir">Transferir</a>
    <a class="btn btn-primary" role="button" asp-controller="Transacao" asp-action="Saque">Saque</a>
</div>

Views/Transacao/Saque.cshtml
@{
    ViewData["Title"] = "Editar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Retirar Dinheiro</h1>

</div>

<form>
    <div class="form-group">
        <label for="saque"> <h5>Quantidade a Ser Retirado R$</h5> </label>
        <input type="number" class="form-control" placeholder="R$">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Confirmar</button>
    <a class="btn btn-secondary" asp-controller="Transacao" asp-action="Index" role="button">Voltar</a>
</form>

Views/Transacao/Transferir.cshtml
@{
    ViewData["Title"] = "Transferir Dinheiro";
}

<div class="text-center">

    <h1 class="display-4">Transferir Dinheiro</h1>

</div>

<form>

    <div class="form-group">
        <label for="cpf"> <h5>CPF</h5> </label>
        <input type="string" class="form-control" placeholder="R$">
    </div>

    <div class="form-group">
        <label for="deposito"> <h5>Quantidade a ser transferido R$</h5> </label>
        <input type="number" class="form-control" placeholder="R$">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Confirmar</button>
    <a class="btn btn-secondary" asp-controller="Transacao" asp-action="Index" role="button">Voltar</a>
</form>